### PR TITLE
Added Opencode Icon to the app

### LINKED ISSUE #54: Add an icon to the App.
Use the open code icon.

### PR DESCRIPTION
**Pull request by JLodha**
__54__ 

Fixes #54 

#### Short description of what this resolves:
Added the opencode icon to the app

#### Changes proposed in this pull request and/or Screenshots of changes:

- 
Screenshot_20200124-001441
Screenshot_20200124-001450 (1)

-
-

### CODE REVIEW

**Comment by MiKinshu** [comment]
Give screenshots, with PR

**Comment by JLodha** [comment]
Sir please have a look.
Sorry for late response( due to some personal reasons)

**Comment by MiKinshu** [comment]
There are merge conflicts. Please resolve these and put .idea folder in gitignore.

**Comment by JLodha** [comment]
Sir please review the PR once again.
Thanks

**Pull request merged**
