### PR TITLE
added toolbar

### LINKED ISSUE #60: Add a parent and toolbar in settings activity
1. Add a toolbar in settings activity
2. Add main activity as the parent of settings activity

### PR DESCRIPTION
**Pull request by blaze-assault**
__60__ 

Fixes #60 

#### Short description of what this resolves:
added toolbar

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
@blaze-assault Please read about the purpose of the toolbar and where it should be added. You also need to set the toolbar as the app bar for the activity. :/

**Comment by blaze-assault** [comment]
> @blaze-assault Please read about the purpose of the toolbar and where it should be added. You also need to set the toolbar as the app bar for the activity. :/

Sir it just says that add toolbar in settings activity and i did that ..please clarify the task then ..and please reply fast sir as i took the task 4 days ago and made pr two days ago but it was  reviewed  late.

**Comment by shiv07tiwari** [comment]
@blaze-assault When a task is opened, we assume that you guys are intelligent enough to do some study on it. ADDING A TOOLBAR doesn't mean add it anywhere in the activity.

**Comment by blaze-assault** [comment]
Sir i understand .but it was clearly written add it in settings activity .

**Comment by shiv07tiwari** [comment]
image
Hope this helps

**Pull request closed without merging**
