### PR TITLE
added opencode icon on navigation bar

### LINKED ISSUE #3: Add OpenCode logo in the navigation drawer.

### PR DESCRIPTION
**Pull request by aawizard**
__3__ 

Fixes #3

#### Short description of what this resolves:
added opencode icon in the navigation bar

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
@aawizard 
1. please ensure extra files and changes are not in the PR.
2. Resolve the merge conflict.

**Comment by aawizard** [comment]
sir, please help me how to resolve the issue

**Comment by shiv07tiwari** [comment]
@aawizard You need to remove the extra files before pushing. https://stackoverflow.com/a/46571620/9861187

**Comment by aawizard** [comment]
now i have deleted extra files, please go through it again

**Comment by MiKinshu** [comment]
Attach SS from next time onwards.

**Pull request merged**
