### PR TITLE
Created new Blank fragment and Added it in Main Activity

### LINKED ISSUE #2: Create a new blank fragment and add it to MainActivity. Make sure it is added dynamically.

### PR DESCRIPTION
**Pull request by animesh328**
__2__ 

Fixes #2 

#### Short description of what this resolves:
Created new Blank fragment and Added it in Main Activity.
Annotation 2020-01-18 161709

#### Changes proposed in this pull request and/or Screenshots of changes:

-Added Change
-
-

### CODE REVIEW

**Comment by MiKinshu** [comment]
Add the fragment in a container so that it can be replaced with other fragments as per requirements.

**Comment by animesh328** [comment]
> Add the fragment in a container so that it can be replaced with other fragments as per requirements.

Can you please elaborate ???I am not getting it??
Please explain a bit more

**Comment by MiKinshu** [comment]
Rn you have added a fragment to the xml of mainactivity. This is not a good practice. You should always add a container and add the fragment in that container. This allows us to change the fragment dynamically.

**Comment by animesh328** [comment]
> Rn you have added a fragment to the xml of mainactivity. This is not a good practice. You should always add a container and add the fragment in that container. This allows us to change the fragment dynamically.

Sir,I have added a container and fragment in than container.
Please check it

**Comment by Cybertron-Avneesh** [comment]
can i work on it?

**Pull request closed without merging**
